name = "resume-tailor"
pages_build_output_dir = ".pages-deploy"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXTAUTH_URL = "https://resume-tailor-6sx.pages.dev"
NODE_ENV = "production"
